model:
  cls: models.diffusion.Diffusion
  base_learning_rate: 0.0001
  params:
    log_every_t: 100
    save_every_n_epochs: 1
    timesteps: 1000
    image_size: 32
    channels: 3
    scheduler_config:
      cls: schedulers.LinearScheduler
      params:
        step_size: 1000
        gamma: 0.98
    unet_config:
      cls: modules.unet.UNet
      params:
        channels: 128
        depth: 4
        dropout: 0.1
        use_attention: false
    optimizer_config:
      cls: torch.optim.Adam
      params:
        lr: 0.0001
        betas: [0.9, 0.999]
        eps: 1e-8
        weight_decay: 0.0
dataset:
  cls: dataset.anime_faces.AnimeFacesDataset